# -*- coding: utf-8 -*-
"""phase_1_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eG0baiQUoXow4bVtGhMS5KkbRa2QYhBU

# E-Commerce Sales Performance Analysis

## Phase 1 Mini Project
### Real-World Data Analysis and Exploratory Data Analysis (EDA)

**Student Name:** Yash Dadhich

**Objective:**
Analyze e-commerce sales data to identify sales trends, customer behavior, product performance, seller performance, and business insights.
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

plt.style.use('ggplot')

from google.colab import files

uploaded = files.upload()

customers = pd.read_csv("olist_customers_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
category = pd.read_csv("product_category_name_translation.csv")

print("Customers Shape:", customers.shape)
print("Orders Shape:", orders.shape)
print("Order Items Shape:", order_items.shape)
print("Products Shape:", products.shape)
print("Payments Shape:", payments.shape)
print("Reviews Shape:", reviews.shape)
print("Sellers Shape:", sellers.shape)

customers.head()
orders.head()
products.head()

customers.info()
orders.info()

print("CUSTOMERS")
print(customers.isnull().sum())

print("\nORDERS")
print(orders.isnull().sum())

print("\nPRODUCTS")
print(products.isnull().sum())

print("Customers:", customers.duplicated().sum())
print("Orders:", orders.duplicated().sum())
print("Products:", products.duplicated().sum())

orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

df = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

df = df.merge(
    order_items,
    on="order_id",
    how="left"
)

df = df.merge(
    products,
    on="product_id",
    how="left"
)

df = df.merge(
    category,
    on="product_category_name",
    how="left"
)

df = df.merge(
    payments,
    on="order_id",
    how="left"
)

df = df.merge(
    reviews,
    on="order_id",
    how="left"
)

df.shape

df[['payment_value']].head()

category_revenue = (
    df.groupby(
        "product_category_name_english"
    )["payment_value"]
    .sum()
    .sort_values(ascending=False)
)

category_revenue.head(10)

plt.figure(figsize=(12,6))

category_revenue.head(10).plot(
    kind='bar'
)

plt.title("Top 10 Revenue Generating Categories")
plt.xlabel("Category")
plt.ylabel("Revenue")

plt.show()

city_sales = (
    df.groupby("customer_city")
    ["payment_value"]
    .sum()
    .sort_values(ascending=False)
)

city_sales.head(10)

plt.figure(figsize=(12,6))

city_sales.head(10).plot(
    kind='bar'
)

plt.title("Top Cities by Revenue")
plt.xlabel("City")
plt.ylabel("Revenue")

plt.show()

customer_value = (
    df.groupby(
        "customer_unique_id"
    )["payment_value"]
    .sum()
)

customer_value.describe()

purchase_frequency = (
    df.groupby("customer_unique_id")
    .size()
)

purchase_frequency.head()

top_products = (
    df.groupby("product_id")
    ["payment_value"]
    .sum()
    .sort_values(ascending=False)
)

top_products.head(10)

top_products.head(10).plot(
    kind='bar',
    figsize=(12,6)
)

plt.title("Top Products by Revenue")
plt.show()

payment_summary = (
    df.groupby("payment_type")
    ["payment_value"]
    .sum()
)

payment_summary

payment_summary.plot(
    kind='bar',
    figsize=(10,5)
)

plt.title("Payment Method Revenue")
plt.show()

seller_sales = (
    df.groupby("seller_id")
    ["payment_value"]
    .sum()
    .sort_values(ascending=False)
)

seller_sales.head(10)

seller_sales.head(10).plot(
    kind='bar',
    figsize=(12,6)
)

plt.title("Top Sellers")
plt.show()

review_summary = (
    df.groupby(
        "product_category_name_english"
    )["review_score"]
    .mean()
    .sort_values(ascending=False)
)

review_summary.head(10)

plt.figure(figsize=(12,6))

review_summary.head(10).plot(
    kind='bar'
)

plt.title("Highest Rated Categories")

plt.show()

df['month'] = (
    df['order_purchase_timestamp']
    .dt.to_period('M')
)

monthly_sales = (
    df.groupby("month")
    ["payment_value"]
    .sum()
)

monthly_sales.head()

monthly_sales.plot(
    figsize=(14,6)
)

plt.title("Monthly Sales Trend")

plt.show()

repeat_customers = (
    df.groupby("customer_unique_id")
    .size()
)

repeat_count = (
    repeat_customers > 1
).sum()

one_time = (
    repeat_customers == 1
).sum()

print("Repeat Customers:", repeat_count)
print("One Time Customers:", one_time)

missing_values = df.isnull().sum()

missing_values[
    missing_values > 0
]

duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

print("Orders Rows:", orders.shape[0])

print("Merged Rows:", df.shape[0])

df.isnull().sum().sort_values(
    ascending=False
).head(20)

df.describe(include='all')

df.to_csv(
    "cleaned_olist_data.csv",
    index=False
)

print("Dataset Saved Successfully")

from google.colab import files

files.download(
    "cleaned_olist_data.csv"
)

"""# Final Conclusion

1. Identified top revenue generating categories.
2. Determined highest contributing cities.
3. Analyzed customer purchasing behavior.
4. Examined payment preferences.
5. Ranked top sellers.
6. Studied customer reviews.
7. Identified monthly sales trends.
8. Evaluated customer retention.
9. Performed data quality assessment.
10. Validated multi-table data merging.

# Recommendation

- Invest more in top-performing categories.
- Improve low-rated product categories.
- Focus marketing on high-revenue cities.
- Create loyalty programs for repeat customers.
- Strengthen partnerships with top-performing sellers.
"""